=== qlinh120198/Web-Programming-20192/20192-web-programming/Week9/Student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT student (name,id,dob,city,email,phone,school)>
<!ELEMENT name(#PCDATA)>
<!ELEMENT id(#PCDATA)>
<!ELEMENT dob(#PCDATA)>
<!ELEMENT city(#PCDATA)>
<!ELEMENT email(#PCDATA)>
<!ELEMENT phone(#PCDATA)>
<!ELEMENT school(#PCDATA)>

=== qlinh120198/Web-Programming-20192/20192-web-programming/Week9/StudentInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href= "student.css"?>
<!DOCTYPE student SYSTEM "Student.dtd">
<student>
    <name>Name: Nguyen Quang Linh</name>
    <id>Student ID: 20162439</id>
    <dob> DOB: 12 / 01 / 1998 </dob>
    <city>City: Hanoi </city>
    <email>Email: qlinh120198@gmail.com </email>
    <phone>Phone: 0914372236 </phone>
    <school>School: Hanoi University of Science and Technology </school>
</student>
